# Generated by Django 2.1.2 on 2018-12-12 07:33

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='', max_length=100000)),
                ('quantity', models.IntegerField(default=1)),
                ('front_images', models.ImageField(default=None, upload_to=product.models.filepath_front_images)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.models.filepath_images)),
                ('image_for', models.CharField(default=None, max_length=264)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_product', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=models.SET(None), to='product.Type'),
        ),
    ]
