# Generated by Django 2.1.2 on 2018-12-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(default=''),
        ),
    ]
