# Generated by Django 2.1.2 on 2018-12-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('product', '0003_auto_20181218_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project'),
        ),
    ]
