# Generated by Django 2.1.2 on 2019-01-04 14:51

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20181229_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='front_images',
            field=models.ImageField(default=None, upload_to=product.models.filepath_front_images, validators=[product.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_product', to='product.Product', validators=[product.models.validate_image]),
        ),
    ]
