# Generated by Django 2.1.2 on 2018-12-19 16:24

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=165)),
                ('location', models.TextField()),
                ('target_fund', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fund', models.DecimalField(decimal_places=2, max_digits=15)),
                ('area', models.CharField(max_length=65)),
                ('about_this_project', models.TextField()),
                ('image', models.ImageField(upload_to=project.models.filepath_front_images)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=165)),
                ('images', models.ImageField(upload_to=project.models.filepath_images)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
