# Generated by Django 2.1.2 on 2018-12-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
