# Generated by Django 2.1.2 on 2019-01-04 12:01

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20181224_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1920x1080', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
