# Generated by Django 2.1.2 on 2019-01-04 12:32

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to=project.models.filepath_front_images, validators=[project.models.validate_image]),
        ),
    ]
