# Generated by Django 2.1.2 on 2019-01-04 14:51

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190104_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_project', to='project.Project', validators=[project.models.validate_image]),
        ),
    ]
