# Generated by Django 2.1.2 on 2019-01-10 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usersupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupport',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 10, 11, 15, 8, 207180, tzinfo=utc)),
        ),
    ]
