# Generated by Django 2.1.2 on 2019-01-10 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usersupport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersupport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
