# Generated by Django 2.1.2 on 2019-01-10 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190110_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersupport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
